### ISSUE TITLE
WebSocket panic - concurrent write to websocket connection

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#14]
**2017-01-08T18:46:32.51-0500 [App/0]      ERR panic: concurrent write to websocket connection**
2017-01-08T18:46:32.51-0500 [App/0]      ERR goroutine 809 [running]:
2017-01-08T18:46:32.51-0500 [App/0]      ERR panic(0x670ea0, 0xc420400150)
2017-01-08T18:46:32.51-0500 [App/0]      ERR 	/usr/local/go/src/runtime/panic.go:500 +0x1a1
2017-01-08T18:46:32.51-0500 [App/0]      ERR github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc42003bef8, 0x1, 0x0, 0x0, 0x0, 0xc420458500, 0x4a5060)
2017-01-08T18:46:32.51-0500 [App/0]      ERR 	/go/src/github.com/gorilla/websocket/conn.go:539 +0x506
2017-01-08T18:46:32.51-0500 [App/0]      ERR github.com/gorilla/websocket.(*Conn).WriteMessage(0xc42000e780, 0x9, 0x0, 0x0, 0x0, 0x0, 0x45d6e1)
2017-01-08T18:46:32.51-0500 [App/0]      ERR 	/go/src/github.com/gorilla/websocket/conn.go:675 +0x282
2017-01-08T18:46:32.51-0500 [App/0]      ERR github.build.ge.com/212359746/ec-agent/core.KeepAlive.func1.2(0xc420400148, 0xc4203d4c90)
2017-01-08T18:46:32.51-0500 [App/0]      ERR 	/go/src/github.build.ge.com/212359746/ec-agent/core/gateway.go:533 +0x77
2017-01-08T18:46:32.51-0500 [App/0]      ERR created by github.build.ge.com/212359746/ec-agent/core.KeepAlive.func1
2017-01-08T18:46:32.51-0500 [App/0]      ERR 	/go/src/github.build.ge.com/212359746/ec-agent/core/gateway.go:543 +0x85
------------

**Super connection is not retired..**

---------
2017-01-08T18:49:10.00-0500 [App/0]      OUT  [EC Debug] 2017/01/08 23:49:10 string=>https://6ec17280-e43d-4729-9dca-d237ae7a17db.run.aws-usw02-pr.ice.predix.io/v1/api/token/validate
2017-01-08T18:49:10.00-0500 [App/0]      OUT  [EC Debug] 2017/01/08 23:49:10 http.Header=>map[Authorization:[Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImxlZ2FjeS10b2tlbi1rZXkiLCJ0eXAiOiJKV1QifQ.eyJqdGkiOiIxYzU4OTU2OTRjZWQ0Y2VkYjY3OWJhNTI5NjcwYTk0NCIsInN1YiI6ImVjLWFnZW50Iiwic2NvcGUiOlsiZW50ZXJwcmlzZS1jb25uZWN0LnpvbmVzLjZlYzE3MjgwLWU0M2QtNDcyOS05ZGNhLWQyMzdhZTdhMTdkYi51c2VyIiwidWFhLnJlc291cmNlIiwib3BlbmlkIiwidWFhLm5vbmUiXSwiY2xpZW50X2lkIjoiZWMtYWdlbnQiLCJjaWQiOiJlYy1hZ2VudCIsImF6cCI6ImVjLWFnZW50IiwiZ3JhbnRfdHlwZSI6ImNsaWVudF9jcmVkZW50aWFscyIsInJldl9zaWciOiJmMjJiZmJiZSIsImlhdCI6MTQ4MzkxOTEwNiwiZXhwIjoxNDgzOTYyMzA2LCJpc3MiOiJodHRwczovLzBlYzY4M2VmLTM1NzktNGE4ZS05YzAxLWE2OTg0YjRkOWVjMy5wcmVkaXgtdWFhLnJ1bi5hd3MtdXN3MDItcHIuaWNlLnByZWRpeC5pby9vYXV0aC90b2tlbiIsInppZCI6IjBlYzY4M2VmLTM1NzktNGE4ZS05YzAxLWE2OTg0YjRkOWVjMyIsImF1ZCI6WyJ1YWEiLCJlYy1hZ2VudCIsIm9wZW5pZCIsImVudGVycHJpc2UtY29ubmVjdC56b25lcy42ZWMxNzI4MC1lNDNkLTQ3MjktOWRjYS1kMjM3YWU3YTE3ZGIiXX0.ZIp67vaBUchtFD9dR0UfBKxENAZyGw6hEkfGNVEtfjyJMWB_TMA25-JyQ6WvnDdp1eKSnZKaOErl_cNvoAP-d4CmieN5KrWadFn81RvFOlhqkeIZlfbhGdWoOqW9SzppPZqDYbcPwTfUlGKGDR19b9f9MAY86vDQWbyJInhcPf-G15xf6zdxt0EGBAjXUUPKRwUQTX7n9giDle9j2sDmBlXIIgWpUA0LPoAO1ciswGUiIt4wZIlmyGIZ84l2VwyDgldQI3xJHlllhtZ3IpTVBImzU1jMljGzQ04j5Facu37SbeP4YmiClsJqC61wo3ZRlqNLY6OQz4M5-TYODWlhgQ] Predix-Zone-Id:[6ec17280-e43d-4729-9dca-d237ae7a17db]]
**2017-01-08T18:49:10.53-0500 [App/0]      OUT  [EC Gateway] 2017/01/08 23:49:10 super connection not found with the bindId:UMMsSu4XRr, serverId:191001**

**Comment by chiacchang** [comment]
Investigating.

**Comment by chiacchang** [comment]
Bug identified. Rolling out the patch fix in next release. Thanks @palokam

**Comment by chiacchang** [comment]
Fixed in 1.2.77 https://github.com/Enterprise-connect/ec-sdk/releases/tag/v1.2.77

**Comment by chiacchang** [comment]
Issue identified on the server side as well per Brian W. Paul K.

**Comment by chiacchang** [comment]
A fix candidate towards the concurrent map writing issue has been tagged. Please upgrade your version and see if the issue persists.

**Comment by palokam** [comment]
Closed now, marked as duplicate
