### ISSUE TITLE
Gateway Panic 

### ISSUE THREAD

**Issue by plake06** [Enterprise-connect/ec-sdk#28]
Deployed ecAgent gateway and Server together as one droplet in cloud foundry. Then scaled up two two instances. When trying to connect to both instances I was able to only connect to one gateway as the second instance gateway panicked and produced the below output. 

`2017-05-02T14:40:22.79-0400 [App/1]      OUT  [EC Gateway] 2017/05/02 18:40:22 interface conversion: interface {} is nil, not *core.Agent
2017-05-02T14:40:22.79-0400 [App/1]      ERR 2017/05/02 18:40:22 http: response.WriteHeader on hijacked connection
2017-05-02T14:40:22.79-0400 [App/1]      ERR 2017/05/02 18:40:22 http: panic serving 10.72.131.10:3446: interface conversion: interface is *runtime.TypeAssertionError, not string
2017-05-02T14:40:22.79-0400 [App/1]      ERR goroutine 61 [running]:
2017-05-02T14:40:22.79-0400 [App/1]      ERR net/http.(*conn).serve.func1(0xc4202d0880)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/usr/local/go/src/net/http/server.go:1491 +0x12a
2017-05-02T14:40:22.79-0400 [App/1]      ERR panic(0x69eec0, 0xc42037fa00)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/usr/local/go/src/runtime/panic.go:458 +0x243
2017-05-02T14:40:22.79-0400 [App/1]      ERR github.build.ge.com/212359746/ec-agent/core.(*Gateway).ECRequest.func1(0x820280, 0xc420076680)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/go/src/github.build.ge.com/212359746/ec-agent/core/gateway.go:75 +0xdd
2017-05-02T14:40:22.79-0400 [App/1]      ERR panic(0x69eec0, 0xc42037f880)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/usr/local/go/src/runtime/panic.go:458 +0x243
2017-05-02T14:40:22.79-0400 [App/1]      ERR github.build.ge.com/212359746/ec-agent/core.(*Gateway).ECRequest(0xc4204141e0, 0x820280, 0xc420076680, 0xc42012ee10)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/go/src/github.build.ge.com/212359746/ec-agent/core/gateway.go:215 +0xd6c
2017-05-02T14:40:22.79-0400 [App/1]      ERR github.build.ge.com/212359746/ec-agent/core.(*Gateway).ECRequest-fm(0x820280, 0xc420076680, 0xc42012ee10)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/go/src/github.build.ge.com/212359746/ec-agent/core/gateway.go:552 +0x48
2017-05-02T14:40:22.79-0400 [App/1]      ERR net/http.HandlerFunc.ServeHTTP(0xc4204041b0, 0x820280, 0xc420076680, 0xc42012ee10)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/usr/local/go/src/net/http/server.go:1726 +0x44
2017-05-02T14:40:22.79-0400 [App/1]      ERR net/http.(*ServeMux).ServeHTTP(0x83bf40, 0x820280, 0xc420076680, 0xc42012ee10)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/usr/local/go/src/net/http/server.go:2022 +0x7f
2017-05-02T14:40:22.79-0400 [App/1]      ERR net/http.serverHandler.ServeHTTP(0xc4202d0100, 0x820280, 0xc420076680, 0xc42012ee10)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/usr/local/go/src/net/http/server.go:2202 +0x7d
2017-05-02T14:40:22.79-0400 [App/1]      ERR net/http.(*conn).serve(0xc4202d0880, 0x8207c0, 0xc42037f5c0)
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/usr/local/go/src/net/http/server.go:1579 +0x4b7
2017-05-02T14:40:22.79-0400 [App/1]      ERR created by net/http.(*Server).Serve
2017-05-02T14:40:22.79-0400 [App/1]      ERR 	/usr/local/go/src/net/http/server.go:2293 +0x44d`

**Comment by chiacchang** [comment]
Thanks @plake06 investigating.

**Comment by chiacchang** [comment]
fixed in production build#133, beta build#136 @palokam
