### ISSUE TITLE
panic serving {IP}:{PORT}: interface conversion

### ISSUE THREAD

**Issue by adrian-gonzalez** [Enterprise-connect/ec-sdk#29]
Immediately after starting the ecagent_linux binary using the below command:
./ecagent_linux_sys -mod gateway -lpt ${PORT} -zon "{zone-id-replaced-with-value}" -sst "{gateway-uri-replaced-with-value" -tkn "{ec-service-admin-token-replaced-with-value}" -dbg

... I receive the below error. Please note that I have removed all IP and PORT values and replaced them with the words IP and PORT, but they do show up as expected values.

This occurred recently after I had to download the latest binary for ecagent_linux_sys from this repo. I was not seeing this issue beforehand. Any advice on where to begin looking for the problem?

> 
2017-08-10T13:45:11.97-0700 [RTR/1] OUT host.io - [2017-08-10T20:45:11.977+0000] "GET /agent HTTP/1.1" 101 0 0 "-" "Go-http-client/1.1" "IP:PORT" "IP:PORT" x_forwarded_for:"IP" x_forwarded_proto:"-" vcap_request_id:"73b6bc5a-d20b-4404-67ab-f9f5b706b043" response_time:0.000999831 app_id:"02b4cc6a-f2af-4a8e-afed-05f6cde2efe1" app_index:"-" x_b3_traceid:"9e4d0fa2349f1217" x_b3_spanid:"9e4d0fa2349f1217" x_b3_parentspanid:"-"
  2017-08-10T13:45:11.97-0700 [RTR/1] OUT
  2017-08-10T13:45:11.98-0700 [App/0] OUT  [EC Debug] 2017/08/10 20:45:11 string=>IP
  2017-08-10T13:45:11.98-0700 [App/0] OUT  [EC Gateway] 2017/08/10 20:45:11 ip mulformed: the request port might not be specified. continuing validation..
  2017-08-10T13:45:11.98-0700 [App/0] OUT  [EC Gateway] 2017/08/10 20:45:11 ip passed filtering with x-forward-for.
  2017-08-10T13:45:11.98-0700 [App/0] OUT  [EC Gateway] 2017/08/10 20:45:11 unexpected end of JSON input
  2017-08-10T13:45:11.98-0700 [App/0] ERR 2017/08/10 20:45:11 http: panic serving IP:PORT: interface conversion: interface {} is *json.SyntaxError, not string
  2017-08-10T13:45:11.98-0700 [App/0] ERR goroutine 1126 [running]:
  2017-08-10T13:45:11.98-0700 [App/0] ERR net/http.(*conn).serve.func1(0xc420150280)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/usr/local/go/src/net/http/server.go:1721 +0xd0
  2017-08-10T13:45:11.98-0700 [App/0] ERR panic(0x6e4460, 0xc420292d00)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
  2017-08-10T13:45:11.98-0700 [App/0] ERR github.build.ge.com/212359746/eccore.(*Gateway).ECRequest.func1(0x884ac0, 0xc420260b60)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/go/src/github.build.ge.com/212359746/eccore/gateway.go:97 +0x102
  2017-08-10T13:45:11.98-0700 [App/0] ERR panic(0x6db660, 0xc4201109c0)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
  2017-08-10T13:45:11.98-0700 [App/0] ERR github.build.ge.com/111111111/eccore.(*Gateway).ECRequest(0xc4201165a0, 0x884ac0, 0xc420260b60, 0xc420610800)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/go/src/github.build.ge.com/111111111/eccore/gateway.go:129 +0x1e79
  2017-08-10T13:45:11.98-0700 [App/0] ERR github.build.ge.com/212359746/eccore.(*Gateway).ECRequest-fm(0x884ac0, 0xc420260b60, 0xc420610800)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/go/src/github.build.ge.com/212359746/eccore/gateway.go:628 +0x48
  2017-08-10T13:45:11.98-0700 [App/0] ERR net/http.HandlerFunc.ServeHTTP(0xc4201143f0, 0x884ac0, 0xc420260b60, 0xc420610800)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/usr/local/go/src/net/http/server.go:1942 +0x44
  2017-08-10T13:45:11.98-0700 [App/0] ERR net/http.(*ServeMux).ServeHTTP(0x8b23a0, 0x884ac0, 0xc420260b60, 0xc420610800)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/usr/local/go/src/net/http/server.go:2238 +0x130
  2017-08-10T13:45:11.98-0700 [App/0] ERR net/http.serverHandler.ServeHTTP(0xc4201d84d0, 0x884ac0, 0xc420260b60, 0xc420610800)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/usr/local/go/src/net/http/server.go:2568 +0x92
  2017-08-10T13:45:11.98-0700 [App/0] ERR net/http.(*conn).serve(0xc420150280, 0x884f80, 0xc420292b80)
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/usr/local/go/src/net/http/server.go:1825 +0x612
  2017-08-10T13:45:11.98-0700 [App/0] ERR created by net/http.(*Server).Serve
  2017-08-10T13:45:11.98-0700 [App/0] ERR 	/usr/local/go/src/net/http/server.go:2668 +0x2ce
>

**Comment by chiacchang** [comment]
could you advise on your service version, agent version?

**Comment by adrian-gonzalez** [comment]
My EC Agent mode Gateway: v1.125_kamakura
My EC Agent mode Server: v1.121_fukuoka
My EC Agent mode Client: v1.125_kamakura

**Comment by chiacchang** [comment]
It seems to be a LBer issue, the new agent artifact requires the Diego cell enabling in CF.

**Comment by adrian-gonzalez** [comment]
Tried that too. Created a new gateway, and then ran `cf enable-diego App_Name`. After restaging the application I received the below error:

`   2017-08-10T16:57:21.17-0700 [RTR/2] OUT ec-kafka-gateway.run.aws-usw02-pr.ice.predix.io - [2017-08-10T23:57:21.168+0000] "GET /agent HTTP/1.1" 101 0 0 "-" "Go-http-client/1.1" "10.72.11.214:8427" "10.72.5.160:60624" x_forwarded_for:"10.72.11.214" x_forwarded_proto:"-" vcap_request_id:"749cb4d6-1ecb-4186-7d06-2b411adb0402" response_time:0.001888152 app_id:"916dd400-9b56-4814-bf51-c76cc58dc75d" app_index:"0" x_b3_traceid:"19d76b8216629d0b" x_b3_spanid:"19d76b8216629d0b" x_b3_parentspanid:"-"
   2017-08-10T16:57:21.17-0700 [RTR/2] OUT
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 2017/08/10 23:57:21 http: panic serving 10.72.1.12:28522: interface conversion: interface {} is *json.SyntaxError, not string
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] OUT  [EC Debug] 2017/08/10 23:57:21 string=>IP
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] OUT  [EC Gateway] 2017/08/10 23:57:21 ip mulformed: the request port might not be specified. continuing validation..
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] OUT  [EC Gateway] 2017/08/10 23:57:21 ip passed filtering with x-forward-for.
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] OUT  [EC Gateway] 2017/08/10 23:57:21 unexpected end of JSON input
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR goroutine 111 [running]:
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR net/http.(*conn).serve.func1(0xc420202280)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/usr/local/go/src/net/http/server.go:1721 +0xd0
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR panic(0x6e4460, 0xc420188780)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR github.build.ge.com/212359746/eccore.(*Gateway).ECRequest.func1(0x884ac0, 0xc4201261c0)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/go/src/github.build.ge.com/212359746/eccore/gateway.go:97 +0x102
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR panic(0x6db660, 0xc42018c8a0)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR github.build.ge.com/212359746/eccore.(*Gateway).ECRequest(0xc4200153b0, 0x884ac0, 0xc4201261c0, 0xc4200f2400)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/go/src/github.build.ge.com/212359746/eccore/gateway.go:129 +0x1e79
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR github.build.ge.com/ChangSSO/eccore.(*Gateway).ECRequest-fm(0x884ac0, 0xc4201261c0, 0xc4200f2400)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/go/src/github.build.ge.com/ChangSSO/eccore/gateway.go:628 +0x48
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR net/http.HandlerFunc.ServeHTTP(0xc42012f4c0, 0x884ac0, 0xc4201261c0, 0xc4200f2400)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/usr/local/go/src/net/http/server.go:1942 +0x44
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR net/http.(*ServeMux).ServeHTTP(0x8b23a0, 0x884ac0, 0xc4201261c0, 0xc4200f2400)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/usr/local/go/src/net/http/server.go:2238 +0x130
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR net/http.serverHandler.ServeHTTP(0xc4202922c0, 0x884ac0, 0xc4201261c0, 0xc4200f2400)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/usr/local/go/src/net/http/server.go:2568 +0x92
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR net/http.(*conn).serve(0xc420202280, 0x884f80, 0xc420188640)
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/usr/local/go/src/net/http/server.go:1825 +0x612
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR created by net/http.(*Server).Serve
   2017-08-10T16:57:21.19-0700 [APP/PROC/WEB/0] ERR 	/usr/local/go/src/net/http/server.go:2668 +0x2ce`

**Comment by chiacchang** [comment]
could you paste your configuration on both server/client agent?

**Comment by adrian-gonzalez** [comment]
I'll download the latest agent revision right now and redeploy the server and gateway.
What are the configurations that I should look to provide?

**Comment by chiacchang** [comment]
on the server/client side config, you should have something like the following-

 ./ecagent -mod -lpt -aid -tkn..

**Comment by adrian-gonzalez** [comment]
EC Client:
./ecagent_linux -tkn "{long_token}" -oa2 "https://2958858b-8031-49c5-aadb-93f0473081fc.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token" -hst "wss://ec-kafka-gateway.run.aws-usw02-pr.ice.predix.io/agent" -csc "{clientSecret}" -cid "{clientId}" -aid "8X9ZY8" -tid "ooKCZA" -mod "client"
---------
EC Gateway:
./ecagent_linux_sys -mod gateway -lpt ${PORT} -zon "{zone-id of EC service}" -sst "https://{zone-id-of-EC-service}.run.aws-usw02-pr.ice.predix.io" -tkn "YWRtaW46OUVEMTkxdEBJNWEyZTkwNjQtOWUxZi00NWYyLWEwN2EtYTIwYjFkNzNjODZk" -dbg
---------
EC Server:
./ecagent_linux_sys -aid ooKCZA -hst wss://ec-kafka-gateway.run.aws-usw02-pr.ice.predix.io/agent -rht {kafka-ip} -rpt {kafka-port} -cid {clientSecret} -csc {clientId} -oa2 https://2958858b-8031-49c5-aadb-93f0473081fc.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token -dur 30000 -mod server -dbg

**Comment by chiacchang** [comment]
1) assuming both gateway/server were launched successfully in cf. Could you remove the double quotes in the client config and see how it behaves?
2) if 1) not working, could you share the exceptions following your deployment of the latest artifacts?

**Comment by adrian-gonzalez** [comment]
I'll try this, and report back later in the day, will do! Thanks for all the help so far :)

**Comment by chiacchang** [comment]
@adrian-gonzalez please advance your agent rev to the production build#133.

**Comment by palokam** [comment]
fixed @adrian-gonzalez
