### ISSUE TITLE
EC server panic

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/ec-sdk#41]
2017-10-17T22:07:32.34-0400 [APP/0] ERR github.build.ge.com/212359746/eccore.(*Server).Hire.func2(0x8f9dc0, 0xc42041ae00, 0xc420140000)
   2017-10-17T22:07:32.34-0400 [APP/0] ERR net/http.(*ServeMux).ServeHTTP(0x927e60, 0x8f9dc0, 0xc42041ae00, 0xc420140000)
   2017-10-17T22:07:32.34-0400 [APP/0] ERR net/http.serverHandler.ServeHTTP(0xc42008a2c0, 0x8f9dc0, 0xc42041ae00, 0xc420140000)
   2017-10-17T22:07:36.51-0400 [APP/0] ERR net/http.(*conn).serve.func1(0xc420373e00)
   2017-10-17T22:07:36.51-0400 [APP/0] ERR 	/usr/local/go/src/net/http/server.go:1942 +0x44
   2017-10-17T22:07:36.51-0400 [APP/0] ERR net/http.serverHandler.ServeHTTP(0xc42008a2c0, 0x8f9dc0, 0xc420128540, 0xc420140700)
   2017-10-17T22:07:36.51-0400 [APP/0] ERR created by net/http.(*Server).Serve
   2017-10-17T22:07:36.51-0400 [APP/0] ERR 	/usr/local/go/src/net/http/server.go:2668 +0x2ce
   2017-10-17T22:07:36.51-0400 [RTR/2] OUT 
   2017-10-17T22:07:43.14-0400 [APP/0] OUT  [EC Server] 2017/10/18 02:07:43 receive ping. reset the read timeout.
   2017-10-17T22:07:45.21-0400 [APP/0] OUT  [EC Debug] 2017/10/18 02:07:45 string=>gateway list exchange called.
   2017-10-17T22:07:54.11-0400 [APP/0] ERR 	/usr/local/go/src/net/http/server.go:1721 +0xd0
   2017-10-17T22:07:54.11-0400 [APP/0] ERR panic(0x736980, 0xc4200f9740)
   2017-10-17T22:07:54.11-0400 [APP/0] ERR 	/usr/local/go/src/runtime/panic.go:489 +0x2cf
   2017-10-17T22:07:54.11-0400 [APP/0] ERR 	/go/src/github.build.ge.com/212359746/eccore/server.go:108 +0x3f4
   2017-10-17T22:07:54.11-0400 [APP/0] ERR 	/usr/local/go/src/net/http/server.go:1942 +0x44
   2017-10-17T22:07:54.11-0400 [APP/0] ERR 	/usr/local/go/src/net/http/server.go:2238 +0x130
   2017-10-17T22:07:54.11-0400 [APP/0] ERR created by net/http.(*Server).Serve
   2017-10-17T22:07:54.11-0400 [APP/0] ERR 	/usr/local/go/src/net/http/server.go:2668 +0x2ce
   2017-10-17T22:08:19.55-0400 [APP/0] ERR 2017/10/18 02:08:19 http: panic serving 10.131.16.107:47134: interface conversion: interface {} is nil, not string
   2017-10-17T22:08:19.55-0400 [APP/0] ERR goroutine 12393 [running]:
   2017-10-17T22:08:19.55-0400 [APP/0] ERR net/http.(*conn).serve.func1(0xc4200c05a0)
   2017-10-17T22:08:19.55-0400 [APP/0] ERR github.build.ge.com/212359746/eccore.(*Server).Hire.func2(0x8f9dc0, 0xc4201f02a0, 0xc42064dd00)
   2017-10-17T22:08:19.55-0400 [APP/0] ERR 	/usr/local/go/src/net/http/server.go:1942 +0x44
   2017-10-17T22:08:19.55-0400 [APP/0] ERR 	/usr/local/go/src/net/http/server.go:1825 +0x612

**Comment by chiacchang** [comment]
See candidate release https://github.com/Enterprise-connect/ec-sdk/releases/tag/v1.3.2-candidate
